clear

window = uifigure;


CbMF = uicheckbox(window,...
    'Text','Comparaison Male/Femelle',...
    'ValueChangedFcn',@(src,event) disp(src.Value), 'Position',[20 -60 120 20]);

CbMD = uicheckbox(window,...
    'Text','Moyenne',...
    'ValueChangedFcn',@(src,event) disp(src.Value), 'Position',[20 10 120 20]);


CbReg = uicheckbox(window,...
    'Text','Regression',...
    'ValueChangedFcn',@(src,event) disp(src.Value), 'Position',[20 60 120 20]);

CbVar = uicheckbox(window,...
    'Text','Variance',...
    'ValueChangedFcn',@(src,event) disp(src.Value), 'Position',[20 110 120 20]);

CbCumu = uicheckbox(window,...
    'Text','Cumulative',...
    'ValueChangedFcn',@(src,event) disp(src.Value), 'Position',[20 160 120 20]);


uibutton(window,...
    'Text','Lancer analyse',...
    'Position',[200 20 100 30],...
    'ButtonPushedFcn',@(btn,event) Analyse_Nathan_main(CbMF.Value,CbMD.Value,CbReg.Value,CbVar.Value,CbCumu.Value));